version: '3.8'

services:
  server:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: .dockerfiles/backend.dockerfile
    ports:
      - "3000:3000"  # Fixed port mapping syntax
    volumes:
      - ./backend:/app  # Mount backend volume
    environment:
      OLLAMA_URL: "${OLLAMA_URL}"
      DB_URL: "${DB_URL}"
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:root/.ollama
    ports:
      - "7869:11434"  # Fixed port mapping syntax
    volumes:
      - ./ollama:/code  # Mount ollama volume
      - ollama/ollama:/root/.ollama  # Mount ollama/ollama volume
    container_name: ollama
    pull_policy: always  # Fixed typo in 'pull_policy'
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

  bd:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"  # Fixed port mapping syntax
    volumes:
      - db:/var/lib/postgresql/data  # Mount db volume
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false

volumes:
  backend:  # Defined backend volume
  ollama/ollama:  # Defined ollama/ollama volume
  db:  # Defined db volume
